export const organizationsByCountry = {
  "US": [
    "Microsoft Corporation",
    "Apple Inc",
    "Google LLC",
    "Amazon Web Services",
    "Meta Platforms",
    "Tesla Inc",
    "Netflix Inc",
    "Uber Technologies",
    "Airbnb Inc",
    "Salesforce Inc"
  ],
  "CA": [
    "Shopify Inc",
    "BlackBerry Limited",
    "Bombardier Inc",
    "Canadian National Railway",
    "Royal Bank of Canada",
    "Magna International",
    "Brookfield Asset Management",
    "Alimentation Couche-Tard"
  ],
  "GB": [
    "British Petroleum",
    "Vodafone Group",
    "HSBC Holdings",
    "Unilever PLC",
    "AstraZeneca PLC",
    "Rolls-Royce Holdings",
    "BT Group",
    "Tesco PLC",
    "Barclays PLC",
    "Shell PLC"
  ],
  "DE": [
    "SAP SE",
    "Siemens AG",
    "BMW Group",
    "Mercedes-Benz Group",
    "Volkswagen AG",
    "Bosch Group",
    "Deutsche Bank",
    "Allianz SE",
    "BASF SE",
    "Adidas AG"
  ],
  "FR": [
    "LVMH",
    "L'Oréal Group",
    "Total Energies",
    "Sanofi",
    "Airbus SE",
    "BNP Paribas",
    "Schneider Electric",
    "Danone",
    "Orange SA",
    "Capgemini"
  ],
  "IT": [
    "Eni SpA",
    "Enel SpA",
    "Intesa Sanpaolo",
    "UniCredit Group",
    "Ferrari NV",
    "Prada Group",
    "Telecom Italia",
    "Generali Group",
    "Fiat Chrysler"
  ],
  "ES": [
    "Banco Santander",
    "Telefónica SA",
    "Iberdrola SA",
    "Repsol SA",
    "BBVA",
    "Inditex Group",
    "Amadeus IT Group",
    "Ferrovial SA"
  ],
  "NL": [
    "ASML Holding",
    "Royal Dutch Shell",
    "Unilever NV",
    "ING Group",
    "Philips",
    "Heineken NV",
    "RELX Group",
    "Prosus NV"
  ],
  "JP": [
    "Toyota Motor Corporation",
    "Sony Corporation",
    "Nintendo Co Ltd",
    "SoftBank Group",
    "Honda Motor Co",
    "Panasonic Corporation",
    "Mitsubishi Corporation",
    "Canon Inc",
    "Nissan Motor Co",
    "Rakuten Group"
  ],
  "KR": [
    "Samsung Electronics",
    "LG Electronics",
    "Hyundai Motor Company",
    "SK Hynix",
    "POSCO Holdings",
    "Kia Corporation",
    "Naver Corporation",
    "Kakao Corp"
  ],
  "CN": [
    "Alibaba Group",
    "Tencent Holdings",
    "ByteDance Ltd",
    "Baidu Inc",
    "JD.com Inc",
    "Xiaomi Corporation",
    "Huawei Technologies",
    "BYD Company",
    "Meituan",
    "NetEase Inc"
  ],
  "IN": [
    "Tata Consultancy Services",
    "Infosys Limited",
    "Wipro Limited",
    "Reliance Industries",
    "HDFC Bank",
    "Indian Oil Corporation",
    "State Bank of India",
    "Bharti Airtel",
    "Tech Mahindra",
    "HCL Technologies"
  ],
  "AU": [
    "Commonwealth Bank",
    "BHP Group",
    "CSL Limited",
    "Westpac Banking Corporation",
    "ANZ Banking Group",
    "Woolworths Group",
    "Rio Tinto Group",
    "Telstra Corporation"
  ],
  "BR": [
    "Petrobras",
    "Vale SA",
    "Itaú Unibanco",
    "Banco do Brasil",
    "JBS SA",
    "Magazine Luiza",
    "Ambev SA",
    "Suzano SA"
  ],
  "SG": [
    "DBS Group Holdings",
    "Singapore Airlines",
    "Oversea-Chinese Banking Corp",
    "United Overseas Bank",
    "CapitaLand Limited",
    "Genting Singapore",
    "Sea Limited"
  ]
};

export const countries = [
  { code: "US", name: "United States" },
  { code: "CA", name: "Canada" },
  { code: "GB", name: "United Kingdom" },
  { code: "DE", name: "Germany" },
  { code: "FR", name: "France" },
  { code: "IT", name: "Italy" },
  { code: "ES", name: "Spain" },
  { code: "NL", name: "Netherlands" },
  { code: "BE", name: "Belgium" },
  { code: "CH", name: "Switzerland" },
  { code: "AT", name: "Austria" },
  { code: "SE", name: "Sweden" },
  { code: "NO", name: "Norway" },
  { code: "DK", name: "Denmark" },
  { code: "FI", name: "Finland" },
  { code: "PL", name: "Poland" },
  { code: "CZ", name: "Czech Republic" },
  { code: "HU", name: "Hungary" },
  { code: "SK", name: "Slovakia" },
  { code: "SI", name: "Slovenia" },
  { code: "HR", name: "Croatia" },
  { code: "RO", name: "Romania" },
  { code: "BG", name: "Bulgaria" },
  { code: "GR", name: "Greece" },
  { code: "PT", name: "Portugal" },
  { code: "IE", name: "Ireland" },
  { code: "LU", name: "Luxembourg" },
  { code: "MT", name: "Malta" },
  { code: "CY", name: "Cyprus" },
  { code: "EE", name: "Estonia" },
  { code: "LV", name: "Latvia" },
  { code: "LT", name: "Lithuania" },
  { code: "JP", name: "Japan" },
  { code: "KR", name: "South Korea" },
  { code: "CN", name: "China" },
  { code: "IN", name: "India" },
  { code: "AU", name: "Australia" },
  { code: "NZ", name: "New Zealand" },
  { code: "SG", name: "Singapore" },
  { code: "HK", name: "Hong Kong" },
  { code: "TW", name: "Taiwan" },
  { code: "TH", name: "Thailand" },
  { code: "MY", name: "Malaysia" },
  { code: "ID", name: "Indonesia" },
  { code: "PH", name: "Philippines" },
  { code: "VN", name: "Vietnam" },
  { code: "BR", name: "Brazil" },
  { code: "MX", name: "Mexico" },
  { code: "AR", name: "Argentina" },
  { code: "CL", name: "Chile" },
  { code: "CO", name: "Colombia" },
  { code: "PE", name: "Peru" },
  { code: "UY", name: "Uruguay" },
  { code: "ZA", name: "South Africa" },
  { code: "EG", name: "Egypt" },
  { code: "MA", name: "Morocco" },
  { code: "NG", name: "Nigeria" },
  { code: "KE", name: "Kenya" },
  { code: "GH", name: "Ghana" },
  { code: "IL", name: "Israel" },
  { code: "AE", name: "United Arab Emirates" },
  { code: "SA", name: "Saudi Arabia" },
  { code: "TR", name: "Turkey" },
  { code: "RU", name: "Russia" },
  { code: "UA", name: "Ukraine" }
];